/* tslint:disable */
/* eslint-disable */
/**
 * Dressca Web API
 * Dressca の Web API 仕様
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AccountResponse } from './account-response';
import { BasketItemResponse } from './basket-item-response';

/**
 * 買い物かごのレスポンスデータを表します。             
 * @export
 * @interface BasketResponse
 */
export interface BasketResponse {
    /**
     * 購入者 Id を取得または設定します。             
     * @type {string}
     * @memberof BasketResponse
     */
    'buyerId': string;
    /**
     * 会計情報を取得または設定します。             
     * @type {AccountResponse}
     * @memberof BasketResponse
     */
    'account'?: AccountResponse | null;
    /**
     * 買い物かごアイテムのリストを取得または設定します。             
     * @type {Array<BasketItemResponse>}
     * @memberof BasketResponse
     */
    'basketItems'?: Array<BasketItemResponse>;
}

