/* tslint:disable */
/* eslint-disable */
/**
 * Dressca Web API
 * Dressca の Web API 仕様
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CatalogItemSummaryDto } from './catalog-item-summary-dto';

/**
 * 買い物かごのアイテムを表す DTO です。             
 * @export
 * @interface BasketItemDto
 */
export interface BasketItemDto {
    /**
     * カタログアイテム Id を取得または設定します。             
     * @type {number}
     * @memberof BasketItemDto
     */
    'catalogItemId': number;
    /**
     * 単価を取得または設定します。             
     * @type {number}
     * @memberof BasketItemDto
     */
    'unitPrice': number;
    /**
     * 数量を取得または設定します。             
     * @type {number}
     * @memberof BasketItemDto
     */
    'quantity': number;
    /**
     * 小計額を取得します。             
     * @type {number}
     * @memberof BasketItemDto
     */
    'subTotal': number;
    /**
     * カタログアイテムを取得または設定します。             
     * @type {CatalogItemSummaryDto}
     * @memberof BasketItemDto
     */
    'catalogItem'?: CatalogItemSummaryDto | null;
}

