/* tslint:disable */
/* eslint-disable */
/**
 * Dressca Web API
 * Dressca の Web API 仕様
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * カタログアイテムの概要を表す DTO です。             
 * @export
 * @interface CatalogItemSummaryDto
 */
export interface CatalogItemSummaryDto {
    /**
     * カタログアイテム Id を取得または設定します。             
     * @type {number}
     * @memberof CatalogItemSummaryDto
     */
    'id': number;
    /**
     * 商品名を取得または設定します。             
     * @type {string}
     * @memberof CatalogItemSummaryDto
     */
    'name': string;
    /**
     * 商品コードを取得または設定します。             
     * @type {string}
     * @memberof CatalogItemSummaryDto
     */
    'productCode': string;
    /**
     * アセットコードの一覧を取得または設定します。             
     * @type {Array<string>}
     * @memberof CatalogItemSummaryDto
     */
    'assetCodes'?: Array<string>;
}

