/* tslint:disable */
/* eslint-disable */
/**
 * Dressca Web API
 * Dressca の Web API 仕様
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * カタログアイテムの DTO です。             
 * @export
 * @interface CatalogItemDtoAllOf
 */
export interface CatalogItemDtoAllOf {
    /**
     * 説明を取得または設定します。             
     * @type {string}
     * @memberof CatalogItemDtoAllOf
     */
    'description': string;
    /**
     * 単価を取得または設定します。             
     * @type {number}
     * @memberof CatalogItemDtoAllOf
     */
    'price': number;
    /**
     * カタログカテゴリ Id を取得または設定します。             
     * @type {number}
     * @memberof CatalogItemDtoAllOf
     */
    'catalogCategoryId': number;
    /**
     * カタログブランド Id を取得または設定します。             
     * @type {number}
     * @memberof CatalogItemDtoAllOf
     */
    'catalogBrandId': number;
}

