/* tslint:disable */
/* eslint-disable */
/**
 * Dressca Web API
 * Dressca の Web API 仕様
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CatalogItemDtoAllOf } from './catalog-item-dto-all-of';
import { CatalogItemSummaryDto } from './catalog-item-summary-dto';

/**
 * @type CatalogItemDto
 * @export
 */
export type CatalogItemDto = CatalogItemDtoAllOf & CatalogItemSummaryDto;


