/* tslint:disable */
/* eslint-disable */
/**
 * Dressca Web API
 * Dressca の Web API 仕様
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AccountDto } from './account-dto';
import { OrderItemDto } from './order-item-dto';

/**
 * 注文情報の DTO です。             
 * @export
 * @interface OrderDto
 */
export interface OrderDto {
    /**
     * 注文 Id を取得または設定します。             
     * @type {number}
     * @memberof OrderDto
     */
    'id'?: number;
    /**
     * 購入者 Id を取得または設定します。             
     * @type {string}
     * @memberof OrderDto
     */
    'buyerId'?: string;
    /**
     * 注文日を取得または設定します。             
     * @type {string}
     * @memberof OrderDto
     */
    'orderDate'?: string;
    /**
     * お届け先氏名を取得または設定します。             
     * @type {string}
     * @memberof OrderDto
     */
    'fullName'?: string;
    /**
     * お届け先郵便番号を取得または設定します。             
     * @type {string}
     * @memberof OrderDto
     */
    'postalCode'?: string;
    /**
     * お届け先都道府県を取得または設定します。             
     * @type {string}
     * @memberof OrderDto
     */
    'todofuken'?: string;
    /**
     * お届け先市区町村を取得または設定します。             
     * @type {string}
     * @memberof OrderDto
     */
    'shikuchoson'?: string;
    /**
     * お届け先字／番地／建物名／部屋番号を取得または設定します。             
     * @type {string}
     * @memberof OrderDto
     */
    'azanaAndOthers'?: string;
    /**
     * 会計情報を取得または設定します。             
     * @type {AccountDto}
     * @memberof OrderDto
     */
    'account'?: AccountDto | null;
    /**
     * 注文アイテムのリストを取得または設定します。             
     * @type {Array<OrderItemDto>}
     * @memberof OrderDto
     */
    'orderItems'?: Array<OrderItemDto>;
}

