/* tslint:disable */
/* eslint-disable */
/**
 * Dressca Web API
 * Dressca の Web API 仕様
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CatalogItemSummaryDto } from './catalog-item-summary-dto';

/**
 * 注文アイテムの DTO です。             
 * @export
 * @interface OrderItemDto
 */
export interface OrderItemDto {
    /**
     * 注文アイテム Id を取得します。             
     * @type {number}
     * @memberof OrderItemDto
     */
    'id': number;
    /**
     * 注文された商品（カタログアイテム）を取得または設定します。             
     * @type {CatalogItemSummaryDto}
     * @memberof OrderItemDto
     */
    'itemOrdered'?: CatalogItemSummaryDto | null;
    /**
     * 単価を取得または設定します。             
     * @type {number}
     * @memberof OrderItemDto
     */
    'unitPrice': number;
    /**
     * 数量を取得または設定します。             
     * @type {number}
     * @memberof OrderItemDto
     */
    'quantity': number;
    /**
     * 小計額を取得します。             
     * @type {number}
     * @memberof OrderItemDto
     */
    'subTotal': number;
}

