/* tslint:disable */
/* eslint-disable */
/**
 * Dressca Web API
 * Dressca の Web API 仕様
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CatalogItemDto } from './catalog-item-dto';

/**
 * ページネーションした結果のリストを管理します。             
 * @export
 * @interface PagedListOfCatalogItemDto
 */
export interface PagedListOfCatalogItemDto {
    /**
     * 現在のページ番号を取得します。 最初のページは 1 です。             
     * @type {number}
     * @memberof PagedListOfCatalogItemDto
     */
    'page'?: number;
    /**
     * ページの総数を取得します。             
     * @type {number}
     * @memberof PagedListOfCatalogItemDto
     */
    'totalPages'?: number;
    /**
     * 1 ページあたりの件数を取得します。             
     * @type {number}
     * @memberof PagedListOfCatalogItemDto
     */
    'pageSize'?: number;
    /**
     * アイテムの総数を取得します。             
     * @type {number}
     * @memberof PagedListOfCatalogItemDto
     */
    'totalCount'?: number;
    /**
     * 前のページが存在するかどうか示す値を取得します。             
     * @type {boolean}
     * @memberof PagedListOfCatalogItemDto
     */
    'hasPrevious'?: boolean;
    /**
     * 次のページが存在するかどうか示す値を取得します。             
     * @type {boolean}
     * @memberof PagedListOfCatalogItemDto
     */
    'hasNext'?: boolean;
    /**
     * 検索結果のリストを取得します。             
     * @type {Array<CatalogItemDto>}
     * @memberof PagedListOfCatalogItemDto
     */
    'items'?: Array<CatalogItemDto>;
}

