/* tslint:disable */
/* eslint-disable */
/**
 * Dressca Web API
 * Dressca の Web API 仕様
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { OrderDto } from '../models';
// @ts-ignore
import { PostOrderInputDto } from '../models';
// @ts-ignore
import { ProblemDetails } from '../models';
/**
 * OrdersApi - axios parameter creator
 * @export
 */
export const OrdersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 注文情報を取得します。
         * @param {number} orderId 注文 Id 。
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersGetById: async (orderId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('ordersGetById', 'orderId', orderId)
            const localVarPath = `/api/orders/{orderId}`
                .replace(`{${"orderId"}}`, encodeURIComponent(String(orderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 買い物かごに登録されている商品を注文します。
         * @param {PostOrderInputDto} postOrderInputDto 注文に必要な配送先などの情報。
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersPostOrder: async (postOrderInputDto: PostOrderInputDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postOrderInputDto' is not null or undefined
            assertParamExists('ordersPostOrder', 'postOrderInputDto', postOrderInputDto)
            const localVarPath = `/api/orders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postOrderInputDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OrdersApi - functional programming interface
 * @export
 */
export const OrdersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OrdersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 注文情報を取得します。
         * @param {number} orderId 注文 Id 。
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ordersGetById(orderId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrderDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ordersGetById(orderId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 買い物かごに登録されている商品を注文します。
         * @param {PostOrderInputDto} postOrderInputDto 注文に必要な配送先などの情報。
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ordersPostOrder(postOrderInputDto: PostOrderInputDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ordersPostOrder(postOrderInputDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * OrdersApi - factory interface
 * @export
 */
export const OrdersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OrdersApiFp(configuration)
    return {
        /**
         * 
         * @summary 注文情報を取得します。
         * @param {number} orderId 注文 Id 。
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersGetById(orderId: number, options?: any): AxiosPromise<OrderDto> {
            return localVarFp.ordersGetById(orderId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 買い物かごに登録されている商品を注文します。
         * @param {PostOrderInputDto} postOrderInputDto 注文に必要な配送先などの情報。
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersPostOrder(postOrderInputDto: PostOrderInputDto, options?: any): AxiosPromise<void> {
            return localVarFp.ordersPostOrder(postOrderInputDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OrdersApi - object-oriented interface
 * @export
 * @class OrdersApi
 * @extends {BaseAPI}
 */
export class OrdersApi extends BaseAPI {
    /**
     * 
     * @summary 注文情報を取得します。
     * @param {number} orderId 注文 Id 。
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApi
     */
    public ordersGetById(orderId: number, options?: AxiosRequestConfig) {
        return OrdersApiFp(this.configuration).ordersGetById(orderId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 買い物かごに登録されている商品を注文します。
     * @param {PostOrderInputDto} postOrderInputDto 注文に必要な配送先などの情報。
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApi
     */
    public ordersPostOrder(postOrderInputDto: PostOrderInputDto, options?: AxiosRequestConfig) {
        return OrdersApiFp(this.configuration).ordersPostOrder(postOrderInputDto, options).then((request) => request(this.axios, this.basePath));
    }
}
