//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maris.ConsoleApp.Hosting.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maris.ConsoleApp.Hosting.Resources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {CommandName} コマンドの実行時に例外が発生し、処理が失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommandExecutorRaiseException {
            get {
                return ResourceManager.GetString("CommandExecutorRaiseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動パラメーター:{CommandParameter} のパースを行います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ParseParameter {
            get {
                return ResourceManager.GetString("ParseParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {CommandName} コマンドのホストの処理を開始します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartHostingService {
            get {
                return ResourceManager.GetString("StartHostingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {CommandName} コマンドのホストの処理が終了コード {ExitCode} で完了しました。実行時間は {ExecutionTime} ms でした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StopHostingService {
            get {
                return ResourceManager.GetString("StopHostingService", resourceCulture);
            }
        }
    }
}
