changelog:
  categories:
    - title: ':newspaper: Features'
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - 内部の改善
          - 不具合
    - title: ':wrench: Bug fixes'
      labels:
        - 不具合
    - title: ':label: :purple_circle: NuGet package dependencies'
      labels:
        - nuget
    - title: ':label: :white_circle: npm package dependencies'
      labels:
        - npm
    - title: ':label: Other dependencies'
      labels:
        - dependencies
      exclude:
        labels:
          - nuget
          - npm
    - title: ':lollipop: improvements in development'
      labels:
        - 内部の改善
