---
default: true
line-length: false

ol-prefix:
  style: "one"
ul-style:
  style: "dash"

ol-indent:
  indent: 4
ul-indent:
  indent: 4

table:
  style: "aligned"

MD025:
  front_matter_title: ""

MD046: false
MD051: false
