customRules:
  - custom-lint-rules/requires-title-and-description.js

gitignore: true

# 全ての md ファイルを対象に markdownlint-cli2 を実行する
globs:
  - "**/*.md"

# md ファイル以外の markdownlint の除外対象を以下に記載する
ignores:
  - "third-party-licenses/**"
  - "LICENSE"
  - "LICENSE-CODE"
