//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dressca.ApplicationCore.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationCoreMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationCoreMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dressca.ApplicationCore.Resources.ApplicationCoreMessages", typeof(ApplicationCoreMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   null または空のリストを設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArgumentIsNullOrEmptyList {
            get {
                return ResourceManager.GetString("ArgumentIsNullOrEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   null または空の文字列を設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArgumentIsNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ArgumentIsNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アセットコード:{0} のアセット情報を取得しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AssetApplicationService_GetAssetStreamInfoEnd {
            get {
                return ResourceManager.GetString("AssetApplicationService_GetAssetStreamInfoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アセットコード:{0} のアセット情報を取得します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AssetApplicationService_GetAssetStreamInfoStart {
            get {
                return ResourceManager.GetString("AssetApplicationService_GetAssetStreamInfoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アセットコード: {0} のアセットが見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AssetNotFound {
            get {
                return ResourceManager.GetString("AssetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0} の買い物かごにカタログアイテム ID: {1} を {2} 個追加しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_AddItemToBasketAsyncEnd {
            get {
                return ResourceManager.GetString("BasketApplicationService_AddItemToBasketAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0} の買い物かごにカタログアイテム ID: {1} を {2} 個追加します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_AddItemToBasketAsyncStart {
            get {
                return ResourceManager.GetString("BasketApplicationService_AddItemToBasketAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0} の買い物かごを削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_DeleteBasketAsyncEnd {
            get {
                return ResourceManager.GetString("BasketApplicationService_DeleteBasketAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0} の買い物かごを削除します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_DeleteBasketAsyncStart {
            get {
                return ResourceManager.GetString("BasketApplicationService_DeleteBasketAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入者 ID: {0} の買い物かご情報を取得または作成しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_GetOrCreateBasketForUserAsyncEnd {
            get {
                return ResourceManager.GetString("BasketApplicationService_GetOrCreateBasketForUserAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入者 ID: {0} の買い物かご情報を取得または作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_GetOrCreateBasketForUserAsyncStart {
            get {
                return ResourceManager.GetString("BasketApplicationService_GetOrCreateBasketForUserAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0} の買い物かごの数量を一括で設定しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_SetQuantitiesAsyncEnd {
            get {
                return ResourceManager.GetString("BasketApplicationService_SetQuantitiesAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0} の買い物かごの数量を一括で設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_SetQuantitiesAsyncStart {
            get {
                return ResourceManager.GetString("BasketApplicationService_SetQuantitiesAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログアイテム ID: {0} の数量を {1} に設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_SetQuantity {
            get {
                return ResourceManager.GetString("BasketApplicationService_SetQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注文のチェックアウト処理開始時、買い物かご内に商品がありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketIsEmptyOnCheckout {
            get {
                return ResourceManager.GetString("BasketIsEmptyOnCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   買い物かごアイテムの数量は 0 未満にできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketItemQuantityMustBePositive {
            get {
                return ResourceManager.GetString("BasketItemQuantityMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0} の買い物かごが見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketNotFound {
            get {
                return ResourceManager.GetString("BasketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログブランド ID: {0} 、カタログカテゴリ ID: {1} のカテゴリ情報を取得しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_GetCatalogItemsAsyncEnd {
            get {
                return ResourceManager.GetString("CatalogApplicationService_GetCatalogItemsAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログブランド ID: {0} 、カタログカテゴリ ID: {1} のカテゴリ情報を取得します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_GetCatalogItemsAsyncStart {
            get {
                return ResourceManager.GetString("CatalogApplicationService_GetCatalogItemsAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログブランド ID は 0 以下にできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogBrandIdMustBePositive {
            get {
                return ResourceManager.GetString("CatalogBrandIdMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログカテゴリ ID は 0 以下にできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogCategoryIdMustBePositive {
            get {
                return ResourceManager.GetString("CatalogCategoryIdMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたカタログアイテム ID: [{0}] のカタログアイテムがリポジトリに存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogItemIdDoesNotExistInRepository {
            get {
                return ResourceManager.GetString("CatalogItemIdDoesNotExistInRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログアイテム ID は 0 以下にできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogItemIdMustBePositive {
            get {
                return ResourceManager.GetString("CatalogItemIdMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入者 ID: {0} の買い物かご情報が見つからなかったため新たに作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateNewBasket_UserBasketNotFound {
            get {
                return ResourceManager.GetString("CreateNewBasket_UserBasketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アセットタイプ: {0} はサポートされていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidAssetType {
            get {
                return ResourceManager.GetString("InvalidAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   買い物かご ID: {0} の情報をもとに注文 ID: {1} を作成しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderApplicationService_CreateOrderAsyncEnd {
            get {
                return ResourceManager.GetString("OrderApplicationService_CreateOrderAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   買い物かご ID: {0} の情報をもとに注文を作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderApplicationService_CreateOrderAsyncStart {
            get {
                return ResourceManager.GetString("OrderApplicationService_CreateOrderAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注文 ID: {0} の注文情報を取得しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderApplicationService_GetOrderAsyncEnd {
            get {
                return ResourceManager.GetString("OrderApplicationService_GetOrderAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注文 ID: {0} の注文情報を取得します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderApplicationService_GetOrderAsyncStart {
            get {
                return ResourceManager.GetString("OrderApplicationService_GetOrderAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0} 、購入者 ID: {1} の注文が見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単価は負の値に設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PriceMustBeZeroOrHigher {
            get {
                return ResourceManager.GetString("PriceMustBeZeroOrHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} プロパティが初期化されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PropertyNotInitialized {
            get {
                return ResourceManager.GetString("PropertyNotInitialized", resourceCulture);
            }
        }
    }
}
