//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dressca.ApplicationCore.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationCoreMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationCoreMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dressca.ApplicationCore.Resources.ApplicationCoreMessages", typeof(ApplicationCoreMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   null または空の文字列を設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArgumentIsNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ArgumentIsNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0} の買い物かごにカタログアイテム ID: {1} を {2} 個追加しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_AddItemToBasketEnd {
            get {
                return ResourceManager.GetString("BasketApplicationService_AddItemToBasketEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0} の買い物かごにカタログアイテム ID: {1} を {2} 個追加します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_AddItemToBasketStart {
            get {
                return ResourceManager.GetString("BasketApplicationService_AddItemToBasketStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0} の買い物かごを削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_DeleteBasketEnd {
            get {
                return ResourceManager.GetString("BasketApplicationService_DeleteBasketEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0} の買い物かごを削除します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_DeleteBasketStart {
            get {
                return ResourceManager.GetString("BasketApplicationService_DeleteBasketStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー ID: {0} の買い物かご情報を取得または作成しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_GetOrCreateBasketForUserEnd {
            get {
                return ResourceManager.GetString("BasketApplicationService_GetOrCreateBasketForUserEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー ID: {0} の買い物かご情報を取得または作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_GetOrCreateBasketForUserStart {
            get {
                return ResourceManager.GetString("BasketApplicationService_GetOrCreateBasketForUserStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログアイテム ID: {0} の数量を {1} に設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_SetQuantities {
            get {
                return ResourceManager.GetString("BasketApplicationService_SetQuantities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0} の買い物かごの数量を一括で設定しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_SetQuantitiesEnd {
            get {
                return ResourceManager.GetString("BasketApplicationService_SetQuantitiesEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0} の買い物かごの数量を一括で設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_SetQuantitiesStart {
            get {
                return ResourceManager.GetString("BasketApplicationService_SetQuantitiesStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   匿名ユーザー: {0} の買い物かご情報をユーザー ID: {1} の買い物かごに追加登録しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_TransferBasketEnd {
            get {
                return ResourceManager.GetString("BasketApplicationService_TransferBasketEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   匿名ユーザー: {0} の買い物かご情報をユーザー ID: {1} の買い物かごに追加登録します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketApplicationService_TransferBasketStart {
            get {
                return ResourceManager.GetString("BasketApplicationService_TransferBasketStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注文のチェックアウト処理開始時、買い物かご内に商品がありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketIsEmptyOnCheckout {
            get {
                return ResourceManager.GetString("BasketIsEmptyOnCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   買い物かごアイテムの数量は 0 未満にできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketItemQuantityMustBePositive {
            get {
                return ResourceManager.GetString("BasketItemQuantityMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0} の買い物かごが見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketNotFound {
            get {
                return ResourceManager.GetString("BasketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログブランド ID: {0} 、カタログカテゴリ ID: {1} のカテゴリ情報を取得しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_GetCatalogEnd {
            get {
                return ResourceManager.GetString("CatalogApplicationService_GetCatalogEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログブランド ID: {0} 、カタログカテゴリ ID: {1} のカテゴリ情報を取得します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_GetCatalogStart {
            get {
                return ResourceManager.GetString("CatalogApplicationService_GetCatalogStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログブランド ID は 0 以下にできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogBrandIdMustBePositive {
            get {
                return ResourceManager.GetString("CatalogBrandIdMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログカテゴリ ID は 0 以下にできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogCategoryIdMustBePositive {
            get {
                return ResourceManager.GetString("CatalogCategoryIdMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログアイテム ID は 0 以下にできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogItemIdMustBePositive {
            get {
                return ResourceManager.GetString("CatalogItemIdMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー ID: {0} の買い物かご情報が見つからなかったため新たに作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateNewBasket_UserBasketNotFound {
            get {
                return ResourceManager.GetString("CreateNewBasket_UserBasketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   買い物かご ID: {0} の情報をもとに注文 ID: {1} を作成しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderApplicationService_CreateOrderAsyncEnd {
            get {
                return ResourceManager.GetString("OrderApplicationService_CreateOrderAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   買い物かご ID: {0} の情報をもとに注文を作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderApplicationService_CreateOrderAsyncStart {
            get {
                return ResourceManager.GetString("OrderApplicationService_CreateOrderAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単価は負の値に設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PriceMustBeZeroOrHigher {
            get {
                return ResourceManager.GetString("PriceMustBeZeroOrHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} プロパティが初期化されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PropertyNotInitialized {
            get {
                return ResourceManager.GetString("PropertyNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー ID: {0} の買い物かごが見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserBasketNotFound {
            get {
                return ResourceManager.GetString("UserBasketNotFound", resourceCulture);
            }
        }
    }
}
