//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dressca.ApplicationCore.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dressca.ApplicationCore.Resources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   アセットコード:{AssetCode} のアセット情報を取得しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AssetApplicationService_GetAssetStreamInfoEnd {
            get {
                return ResourceManager.GetString("AssetApplicationService_GetAssetStreamInfoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アセットコード:{AssetCode} のアセット情報を取得します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AssetApplicationService_GetAssetStreamInfoStart {
            get {
                return ResourceManager.GetString("AssetApplicationService_GetAssetStreamInfoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量設定後の買い物かごアイテム: {BasketItems} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Basket_AfterSettingQuantity {
            get {
                return ResourceManager.GetString("Basket_AfterSettingQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログに カタログアイテムID: {CatalogItemId} のカタログアイテムを追加しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_AddItemToCatalogAsyncEnd {
            get {
                return ResourceManager.GetString("CatalogApplicationService_AddItemToCatalogAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログにアイテムを追加します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_AddItemToCatalogAsyncStart {
            get {
                return ResourceManager.GetString("CatalogApplicationService_AddItemToCatalogAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログアイテム ID: {CatalogItemId} のカタログアイテムを削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_DeleteItemFromCatalogAsyncEnd {
            get {
                return ResourceManager.GetString("CatalogApplicationService_DeleteItemFromCatalogAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログアイテム ID: {CatalogItemId} のカタログアイテムを削除します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_DeleteItemFromCatalogAsyncStart {
            get {
                return ResourceManager.GetString("CatalogApplicationService_DeleteItemFromCatalogAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理者がカタログアイテム ID: {CatalogItemId} のカタログアイテムを取得しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_GetCatalogItemForAdminAsyncEnd {
            get {
                return ResourceManager.GetString("CatalogApplicationService_GetCatalogItemForAdminAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理者がカタログアイテム ID: {CatalogItemId} のカタログアイテムを取得します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_GetCatalogItemForAdminAsyncStart {
            get {
                return ResourceManager.GetString("CatalogApplicationService_GetCatalogItemForAdminAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログブランド ID: {CatalogBrandId} 、カタログカテゴリ ID: {CatalogCategoryId} のカテゴリ情報を取得しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_GetCatalogItemsAsyncEnd {
            get {
                return ResourceManager.GetString("CatalogApplicationService_GetCatalogItemsAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログブランド ID: {CatalogBrandId} 、カタログカテゴリ ID: {CatalogCategoryId} のカテゴリ情報を取得します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_GetCatalogItemsAsyncStart {
            get {
                return ResourceManager.GetString("CatalogApplicationService_GetCatalogItemsAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理者がカタログブランド ID: {CatalogBrandId} 、カタログカテゴリ ID: {CatalogCategoryId} のカタログ情報を取得しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_GetCatalogItemsForAdminAsyncEnd {
            get {
                return ResourceManager.GetString("CatalogApplicationService_GetCatalogItemsForAdminAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理者がカタログブランド ID: {CatalogBrandId} 、カタログカテゴリ ID: {CatalogCategoryId} のカタログ情報を取得します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_GetCatalogItemsForAdminAsyncStart {
            get {
                return ResourceManager.GetString("CatalogApplicationService_GetCatalogItemsForAdminAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログアイテム ID: {CatalogItemId} のカタログアイテムを更新しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_UpdateCatalogItemAsyncEnd {
            get {
                return ResourceManager.GetString("CatalogApplicationService_UpdateCatalogItemAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログアイテム ID: {CatalogItemId} のカタログアイテムを更新します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_UpdateCatalogItemAsyncStart {
            get {
                return ResourceManager.GetString("CatalogApplicationService_UpdateCatalogItemAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたカタログブランド ID: [{CatalogBrandId}] のカタログブランドがリポジトリに存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogBrandIdDoesNotExistInRepository {
            get {
                return ResourceManager.GetString("CatalogBrandIdDoesNotExistInRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたカタログカテゴリ ID: [{CatalogCategoryId}] のカタログカテゴリがリポジトリに存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogCategoryIdDoesNotExistInRepository {
            get {
                return ResourceManager.GetString("CatalogCategoryIdDoesNotExistInRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたカタログアイテム ID: [{CatalogItemId}] のカタログアイテムがリポジトリに存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogItemIdDoesNotExistInRepository {
            get {
                return ResourceManager.GetString("CatalogItemIdDoesNotExistInRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入者 ID: {BuyerId} の買い物かご情報が見つからなかったため新たに作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateNewBasket_UserBasketNotFound {
            get {
                return ResourceManager.GetString("CreateNewBasket_UserBasketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注文 ID: {OrderId} の注文情報を取得しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderApplicationService_GetOrderAsyncEnd {
            get {
                return ResourceManager.GetString("OrderApplicationService_GetOrderAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注文 ID: {OrderId} の注文情報を取得します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderApplicationService_GetOrderAsyncStart {
            get {
                return ResourceManager.GetString("OrderApplicationService_GetOrderAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {BasketId} の買い物かごにカタログアイテム ID: {CatalogItemId} を {Quantity} 個追加しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_AddItemToBasketAsyncEnd {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_AddItemToBasketAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {BasketId} の買い物かごにカタログアイテム ID: {CatalogItemId} を {Quantity} 個追加します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_AddItemToBasketAsyncStart {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_AddItemToBasketAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   買い物かご ID: {BasketId} の情報をもとに注文 ID: {OrderId} を作成しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_CheckoutAsyncEnd {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_CheckoutAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   買い物かご ID: {BasketId} の情報をもとに注文を作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_CheckoutAsyncStart {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_CheckoutAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入者 ID: {BuyerId} の買い物かごアイテムの一覧を取得しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_GetBasketItemsAsyncEnd {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_GetBasketItemsAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入者 ID: {BuyerId} の買い物かごアイテムの一覧を取得します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_GetBasketItemsAsyncStart {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_GetBasketItemsAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入者 ID: {BuyerId} の買い物かご情報を取得または作成しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_GetOrCreateBasketForUserAsyncEnd {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_GetOrCreateBasketForUserAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入者 ID: {BuyerId} の買い物かご情報を取得または作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_GetOrCreateBasketForUserAsyncStart {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_GetOrCreateBasketForUserAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {BasketId} の買い物かごの数量を一括で設定しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_SetBasketItemsQuantitiesAsyncEnd {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_SetBasketItemsQuantitiesAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {BasketId} の買い物かごの数量を一括で設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_SetBasketItemsQuantitiesAsyncStart {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_SetBasketItemsQuantitiesAsyncStart", resourceCulture);
            }
        }
    }
}
