//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dressca.ApplicationCore.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dressca.ApplicationCore.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   null または空のリストを設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArgumentIsNullOrEmptyList {
            get {
                return ResourceManager.GetString("ArgumentIsNullOrEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   null または空の文字列を設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArgumentIsNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ArgumentIsNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アセットコード:{assetCode} のアセット情報を取得しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AssetApplicationService_GetAssetStreamInfoEnd {
            get {
                return ResourceManager.GetString("AssetApplicationService_GetAssetStreamInfoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アセットコード:{assetCode} のアセット情報を取得します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AssetApplicationService_GetAssetStreamInfoStart {
            get {
                return ResourceManager.GetString("AssetApplicationService_GetAssetStreamInfoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アセットコード: {0} のアセットが見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AssetNotFound {
            get {
                return ResourceManager.GetString("AssetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量設定後の買い物かごアイテム: {basketItems} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Basket_AfterSettingQuantity {
            get {
                return ResourceManager.GetString("Basket_AfterSettingQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログアイテム ID: {0}, 数量: {1}  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Basket_ItemQuantity {
            get {
                return ResourceManager.GetString("Basket_ItemQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注文のチェックアウト処理開始時、買い物かご内に商品がありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketIsEmptyOnCheckout {
            get {
                return ResourceManager.GetString("BasketIsEmptyOnCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注文のチェックアウト処理開始時、買い物かごが存在しませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketIsNullOnCheckout {
            get {
                return ResourceManager.GetString("BasketIsNullOnCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   買い物かごアイテムの数量は 0 未満にできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasketItemQuantityMustBePositive {
            get {
                return ResourceManager.GetString("BasketItemQuantityMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログブランド ID: {catalogBrandId} 、カタログカテゴリ ID: {catalogCategoryId} のカテゴリ情報を取得しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_GetCatalogItemsAsyncEnd {
            get {
                return ResourceManager.GetString("CatalogApplicationService_GetCatalogItemsAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログブランド ID: {catalogBrandId} 、カタログカテゴリ ID: {catalogCategoryId} のカテゴリ情報を取得します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogApplicationService_GetCatalogItemsAsyncStart {
            get {
                return ResourceManager.GetString("CatalogApplicationService_GetCatalogItemsAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログブランド ID は 0 以下にできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogBrandIdMustBePositive {
            get {
                return ResourceManager.GetString("CatalogBrandIdMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログカテゴリ ID は 0 以下にできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogCategoryIdMustBePositive {
            get {
                return ResourceManager.GetString("CatalogCategoryIdMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログアイテム ID :{0} のカタログアイテムが買い物かごに存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogItemIdDoesNotExistInBasket {
            get {
                return ResourceManager.GetString("CatalogItemIdDoesNotExistInBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたカタログアイテム ID: [{catalogItemId}] のカタログアイテムがリポジトリに存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogItemIdDoesNotExistInRepository {
            get {
                return ResourceManager.GetString("CatalogItemIdDoesNotExistInRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタログアイテム ID は 0 以下にできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CatalogItemIdMustBePositive {
            get {
                return ResourceManager.GetString("CatalogItemIdMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入者 ID: {buyerId} の買い物かご情報が見つからなかったため新たに作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateNewBasket_UserBasketNotFound {
            get {
                return ResourceManager.GetString("CreateNewBasket_UserBasketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アセットタイプ: {0} はサポートされていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidAssetType {
            get {
                return ResourceManager.GetString("InvalidAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注文 ID: {orderId} の注文情報を取得しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderApplicationService_GetOrderAsyncEnd {
            get {
                return ResourceManager.GetString("OrderApplicationService_GetOrderAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注文 ID: {orderId} の注文情報を取得します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderApplicationService_GetOrderAsyncStart {
            get {
                return ResourceManager.GetString("OrderApplicationService_GetOrderAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {0} 、購入者 ID: {1} の注文が見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単価は負の値に設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PriceMustBeZeroOrHigher {
            get {
                return ResourceManager.GetString("PriceMustBeZeroOrHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} プロパティが初期化されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PropertyNotInitialized {
            get {
                return ResourceManager.GetString("PropertyNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {basketId} の買い物かごにカタログアイテム ID: {catalogItemId} を {quantity} 個追加しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_AddItemToBasketAsyncEnd {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_AddItemToBasketAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {basketId} の買い物かごにカタログアイテム ID: {catalogItemId} を {quantity} 個追加します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_AddItemToBasketAsyncStart {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_AddItemToBasketAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   買い物かご ID: {basketId} の情報をもとに注文 ID: {orderId} を作成しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_CheckoutAsyncEnd {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_CheckoutAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   買い物かご ID: {basketId} の情報をもとに注文を作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_CheckoutAsyncStart {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_CheckoutAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入者 ID: {buyerId} の買い物かごアイテムの一覧を取得しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_GetBasketItemsAsyncEnd {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_GetBasketItemsAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入者 ID: {buyerId} の買い物かごアイテムの一覧を取得します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_GetBasketItemsAsyncStart {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_GetBasketItemsAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入者 ID: {buyerId} の買い物かご情報を取得または作成しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_GetOrCreateBasketForUserAsyncEnd {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_GetOrCreateBasketForUserAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入者 ID: {buyerId} の買い物かご情報を取得または作成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_GetOrCreateBasketForUserAsyncStart {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_GetOrCreateBasketForUserAsyncStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {basketId} の買い物かごの数量を一括で設定しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_SetBasketItemsQuantitiesAsyncEnd {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_SetBasketItemsQuantitiesAsyncEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID: {basketId} の買い物かごの数量を一括で設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShoppingApplicationService_SetBasketItemsQuantitiesAsyncStart {
            get {
                return ResourceManager.GetString("ShoppingApplicationService_SetBasketItemsQuantitiesAsyncStart", resourceCulture);
            }
        }
    }
}
