// <auto-generated />
using System;
using DresscaCMS.Announcement.Infrastructures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DresscaCMS.Announcement.Infrastructures.Migrations
{
    [DbContext(typeof(AnnouncementDbContext))]
    [Migration("20260609065508_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DresscaCMS.Announcement.Infrastructures.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayPriority")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ExpireDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("PostDateTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Announcements", null, t =>
                        {
                            t.HasCheckConstraint("CK_Announcement_DisplayPriority", "[DisplayPriority] IN (1, 2, 3, 4)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000001"),
                            Category = "一般",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 1,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000002"),
                            Category = "一般",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 2,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000003"),
                            Category = "一般",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000004"),
                            Category = "イベント",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 4,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000005"),
                            Category = "イベント",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 1,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000006"),
                            Category = "更新",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 2,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000007"),
                            Category = "更新",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 1, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000008"),
                            Category = "重要",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 4,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000009"),
                            Category = "重要",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 1,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-00000000000a"),
                            Category = "一般",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-00000000000b"),
                            Category = "一般",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 2,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 1, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-00000000000c"),
                            Category = "イベント",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 4,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-00000000000d"),
                            Category = "イベント",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 1,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-00000000000e"),
                            Category = "更新",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 1, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-00000000000f"),
                            Category = "更新",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 2,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 1, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000010"),
                            Category = "一般",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 4,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 1, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000011"),
                            Category = "重要",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 1,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 1, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000012"),
                            Category = "一般",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 1, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000013"),
                            Category = "イベント",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 2,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000014"),
                            Category = "一般",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 1, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000015"),
                            Category = "一般",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 4,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 1, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000016"),
                            Category = "一般",
                            ChangedAt = new DateTimeOffset(new DateTime(2011, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2010, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 1,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2019, 1, 1, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = true,
                            PostDateTime = new DateTimeOffset(new DateTime(2018, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000017"),
                            Category = "テスト",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 4,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2100, 1, 1, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2030, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7001-8001-000000000018"),
                            Category = "テスト",
                            ChangedAt = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 4,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2100, 1, 1, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2030, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("DresscaCMS.Announcement.Infrastructures.Entities.AnnouncementContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnnouncementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("LinkedUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.ToTable("AnnouncementContents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000001"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000001"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 1",
                            Title = "お知らせ 1"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000002"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000002"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 2",
                            Title = "お知らせ 2"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000003"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000003"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 3",
                            Title = "お知らせ 3"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000004"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000004"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 4",
                            Title = "お知らせ 4"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000005"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000005"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 5",
                            Title = "お知らせ 5"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000006"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000006"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 6",
                            Title = "お知らせ 6"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000007"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000007"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 7",
                            Title = "お知らせ 7"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000008"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000008"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 8",
                            Title = "お知らせ 8"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000009"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000009"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 9",
                            Title = "お知らせ 9"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-00000000000a"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-00000000000a"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 10",
                            Title = "お知らせ 10"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-00000000000b"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-00000000000b"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 11",
                            Title = "お知らせ 11"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-00000000000c"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-00000000000c"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 12",
                            Title = "お知らせ 12"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-00000000000d"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-00000000000d"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 13",
                            Title = "お知らせ 13"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-00000000000e"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-00000000000e"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 14",
                            Title = "お知らせ 14"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-00000000000f"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-00000000000f"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 15",
                            Title = "お知らせ 15"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000010"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000010"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 16",
                            Title = "お知らせ 16"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000011"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000011"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 17",
                            Title = "お知らせ 17"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000012"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000012"),
                            LanguageCode = "es",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "Detalles 18",
                            Title = "Anuncio 18"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000013"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000013"),
                            LanguageCode = "zh",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "详情 19",
                            Title = "公告 19"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000014"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000014"),
                            LanguageCode = "en",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "Details 20",
                            Title = "Notice 20"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000015"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000015"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 21",
                            Title = "お知らせ 21"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000016"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000016"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 削除済み",
                            Title = "お知らせ 削除済み"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000017"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000017"),
                            LanguageCode = "en",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容",
                            Title = "英語 English"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000018"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000017"),
                            LanguageCode = "es",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容",
                            Title = "スペイン語 español"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-000000000019"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000018"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容",
                            Title = "日本語"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-00000000001a"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000018"),
                            LanguageCode = "en",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容",
                            Title = "英語 English"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-00000000001b"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000018"),
                            LanguageCode = "zh",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容",
                            Title = "中国語 中文"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7002-8001-00000000001c"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000018"),
                            LanguageCode = "es",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容",
                            Title = "スペイン語 español"
                        });
                });

            modelBuilder.Entity("DresscaCMS.Announcement.Infrastructures.Entities.AnnouncementContentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnnouncementHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("LinkedUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementHistoryId");

                    b.ToTable("AnnouncementContentHistory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000001"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000001"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 1",
                            Title = "お知らせ 1"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000002"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000002"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 2",
                            Title = "お知らせ 2"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000003"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000003"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 3",
                            Title = "お知らせ 3"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000004"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000004"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 4",
                            Title = "お知らせ 4"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000005"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000005"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 5",
                            Title = "お知らせ 5"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000006"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000006"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 6",
                            Title = "お知らせ 6"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000007"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000007"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 7",
                            Title = "お知らせ 7"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000008"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000008"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 8",
                            Title = "お知らせ 8"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000009"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000009"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 9",
                            Title = "お知らせ 9"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-00000000000a"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-00000000000a"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 10",
                            Title = "お知らせ 10"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-00000000000b"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-00000000000b"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 11",
                            Title = "お知らせ 11"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-00000000000c"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-00000000000c"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 12",
                            Title = "お知らせ 12"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-00000000000d"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-00000000000d"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 13",
                            Title = "お知らせ 13"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-00000000000e"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-00000000000e"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 14",
                            Title = "お知らせ 14"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-00000000000f"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-00000000000f"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 15",
                            Title = "お知らせ 15"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000010"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000010"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 16",
                            Title = "お知らせ 16"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000011"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000011"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 17",
                            Title = "お知らせ 17"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000012"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000012"),
                            LanguageCode = "es",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "Detalles 18",
                            Title = "Anuncio 18"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000013"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000013"),
                            LanguageCode = "zh",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "详情 19",
                            Title = "公告 19"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000014"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000014"),
                            LanguageCode = "en",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "Details 20",
                            Title = "Notice 20"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000015"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000015"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 21",
                            Title = "お知らせ 21"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000016"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000016"),
                            LanguageCode = "en",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容",
                            Title = "英語 English"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000017"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000016"),
                            LanguageCode = "es",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容",
                            Title = "スペイン語 español"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000018"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000017"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容",
                            Title = "日本語"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-000000000019"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000017"),
                            LanguageCode = "en",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容",
                            Title = "英語 English"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-00000000001a"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000017"),
                            LanguageCode = "zh",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容",
                            Title = "中国語 中文"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-00000000001b"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000017"),
                            LanguageCode = "es",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容",
                            Title = "スペイン語 español"
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7004-8001-00000000001c"),
                            AnnouncementHistoryId = new Guid("0193ae97-b800-7003-8001-000000000018"),
                            LanguageCode = "ja",
                            LinkedUrl = "https://maris.alesinfiny.org/",
                            Message = "内容 削除済み",
                            Title = "お知らせ 削除済み"
                        });
                });

            modelBuilder.Entity("DresscaCMS.Announcement.Infrastructures.Entities.AnnouncementHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnnouncementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayPriority")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ExpireDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("PostDateTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.ToTable("AnnouncementHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_AnnouncementHistory_DisplayPriority", "[DisplayPriority] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_AnnouncementHistory_OperationType", "[OperationType] IN (0, 1, 2,3)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000001"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000001"),
                            Category = "一般",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 1,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000002"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000002"),
                            Category = "一般",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 2,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000003"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000003"),
                            Category = "一般",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000004"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000004"),
                            Category = "イベント",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 4,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000005"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000005"),
                            Category = "イベント",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 1,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000006"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000006"),
                            Category = "更新",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 2,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000007"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000007"),
                            Category = "更新",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000008"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000008"),
                            Category = "重要",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 4,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000009"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000009"),
                            Category = "重要",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 1,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-00000000000a"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-00000000000a"),
                            Category = "一般",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-00000000000b"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-00000000000b"),
                            Category = "一般",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 2,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-00000000000c"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-00000000000c"),
                            Category = "イベント",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 4,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-00000000000d"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-00000000000d"),
                            Category = "イベント",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 1,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-00000000000e"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-00000000000e"),
                            Category = "更新",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-00000000000f"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-00000000000f"),
                            Category = "更新",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 2,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000010"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000010"),
                            Category = "一般",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 4,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000011"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000011"),
                            Category = "重要",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 1,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000012"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000012"),
                            Category = "一般",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000013"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000013"),
                            Category = "イベント",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 2,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000014"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000014"),
                            Category = "一般",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000015"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000015"),
                            Category = "一般",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 4,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000016"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000017"),
                            Category = "テスト",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 4,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000017"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000018"),
                            Category = "テスト",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 4,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 1,
                            PostDateTime = new DateTimeOffset(new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0193ae97-b800-7003-8001-000000000018"),
                            AnnouncementId = new Guid("0193ae97-b800-7001-8001-000000000016"),
                            Category = "一般",
                            ChangedBy = "system",
                            CreatedAt = new DateTimeOffset(new DateTime(2011, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayPriority = 1,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2019, 1, 1, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            OperationType = 3,
                            PostDateTime = new DateTimeOffset(new DateTime(2018, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("DresscaCMS.Announcement.Infrastructures.Entities.AnnouncementContent", b =>
                {
                    b.HasOne("DresscaCMS.Announcement.Infrastructures.Entities.Announcement", "Announcement")
                        .WithMany("Contents")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Announcement");
                });

            modelBuilder.Entity("DresscaCMS.Announcement.Infrastructures.Entities.AnnouncementContentHistory", b =>
                {
                    b.HasOne("DresscaCMS.Announcement.Infrastructures.Entities.AnnouncementHistory", "AnnouncementHistory")
                        .WithMany("Contents")
                        .HasForeignKey("AnnouncementHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnouncementHistory");
                });

            modelBuilder.Entity("DresscaCMS.Announcement.Infrastructures.Entities.AnnouncementHistory", b =>
                {
                    b.HasOne("DresscaCMS.Announcement.Infrastructures.Entities.Announcement", "Announcement")
                        .WithMany("Histories")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Announcement");
                });

            modelBuilder.Entity("DresscaCMS.Announcement.Infrastructures.Entities.Announcement", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("Histories");
                });

            modelBuilder.Entity("DresscaCMS.Announcement.Infrastructures.Entities.AnnouncementHistory", b =>
                {
                    b.Navigation("Contents");
                });
#pragma warning restore 612, 618
        }
    }
}
