//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DresscaCMS.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DresscaCMS.Web.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   お知らせメッセージを保存しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AnnouncementSaved {
            get {
                return ResourceManager.GetString("AnnouncementSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中国語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お知らせメッセージの登録に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateAnnouncementFailed {
            get {
                return ResourceManager.GetString("CreateAnnouncementFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示優先度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayPriority {
            get {
                return ResourceManager.GetString("DisplayPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   英語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効なメールアドレスを入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnterEmailFormat {
            get {
                return ResourceManager.GetString("EnterEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}はURLの形式で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnterUrlFormat {
            get {
                return ResourceManager.GetString("EnterUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   掲載終了日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpireDateTime {
            get {
                return ResourceManager.GetString("ExpireDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の値が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidEnumValue {
            get {
                return ResourceManager.GetString("InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンク先URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LinkedUrl {
            get {
                return ResourceManager.GetString("LinkedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン試行が無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メッセージ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   掲載開始日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostDateTime {
            get {
                return ResourceManager.GetString("PostDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン状態を保持する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequiredToInput {
            get {
                return ResourceManager.GetString("RequiredToInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequiredToSelect {
            get {
                return ResourceManager.GetString("RequiredToSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お知らせメッセージとお知らせコンテンツの更新に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveAnnouncementFailed {
            get {
                return ResourceManager.GetString("SaveAnnouncementFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お知らせメッセージが取得できていない状態で保存処理が呼び出されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveWasCalledBeforeTheAnnouncementCouldBeRetrieved {
            get {
                return ResourceManager.GetString("SaveWasCalledBeforeTheAnnouncementCouldBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペイン語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー {0} のオブジェクトは {1} です。指定された型 {2} にキャストできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StoredObjectCannotCastTo {
            get {
                return ResourceManager.GetString("StoredObjectCannotCastTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以下で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringLengthIsOver {
            get {
                return ResourceManager.GetString("StringLengthIsOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}以降に設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToBeAfterDate {
            get {
                return ResourceManager.GetString("ToBeAfterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明なユーザー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnknownUser {
            get {
                return ResourceManager.GetString("UnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された言語コード:{0} はサポートされていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnsupportedLanguageCode {
            get {
                return ResourceManager.GetString("UnsupportedLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーがログインしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
    }
}
