// <auto-generated />
using System;
using DresscaCMS.ApplicationCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DresscaCMS.ApplicationCore.Migrations
{
    [DbContext(typeof(DresscaCMSDbContext))]
    partial class DresscaCMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DresscaCMS.ApplicationCore.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("DisplayPriority")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("ExpireDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("PostDateTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2c651dc-e000-473e-b064-8a1e399f93a7"),
                            Category = "メンテナンス",
                            DisplayPriority = (short)3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2024, 9, 15, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("704945e2-ab1f-4a46-b853-d14f09e38ed4"),
                            Category = "障害情報",
                            DisplayPriority = (short)3,
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("c738b93c-06ef-44be-9bb8-87fe0c3f6151"),
                            Category = "新機能・サービス",
                            DisplayPriority = (short)3,
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("5030af08-13b9-478f-96d3-77e68225ebec"),
                            Category = "イベント情報",
                            DisplayPriority = (short)3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2024, 9, 15, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("8721cd7a-f8cb-4d00-b5c8-53ce5eeac062"),
                            Category = "会社情報",
                            DisplayPriority = (short)3,
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("da1cc949-385e-44b3-a7d1-3f489cf2347d"),
                            Category = "会社情報",
                            DisplayPriority = (short)3,
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("9eabc9d8-39af-472b-afbc-1f7e5ac61899"),
                            Category = "メンテナンス",
                            DisplayPriority = (short)3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2024, 9, 15, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("f46e232c-ce77-408d-924e-aeaff126a639"),
                            Category = "障害情報",
                            DisplayPriority = (short)3,
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("85355a45-24d1-4b1d-98cd-d073f2ccfa02"),
                            Category = "新機能・サービス",
                            DisplayPriority = (short)3,
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("06d6b6c6-906c-4de8-a02a-fd0f448d9d2f"),
                            Category = "イベント情報",
                            DisplayPriority = (short)3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2024, 9, 15, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("c948318a-44cf-4e3a-b4a2-33a382570283"),
                            Category = "会社情報",
                            DisplayPriority = (short)3,
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("450a2931-f066-4f64-920a-25d2804c4951"),
                            Category = "会社情報",
                            DisplayPriority = (short)3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2024, 9, 15, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("3ed8bba8-fe95-477c-89ac-0abb586affae"),
                            Category = "障害情報",
                            DisplayPriority = (short)3,
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("5ff8f1f1-29f2-4c55-ad12-90004bcb3003"),
                            Category = "新機能・サービス",
                            DisplayPriority = (short)3,
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("c8180f90-fd55-4d81-9f1e-0946d5c3d75d"),
                            Category = "イベント情報",
                            DisplayPriority = (short)3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2024, 9, 15, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("f83041bb-acb0-4e73-a87f-60646616b6a3"),
                            Category = "重要なお知らせ",
                            DisplayPriority = (short)3,
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("bf62d39d-338d-423e-9f49-e97605c8d157"),
                            Category = "メンテナンス",
                            DisplayPriority = (short)3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2024, 9, 15, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("01182620-90c4-498e-b0a5-1a8b740ff421"),
                            Category = "障害情報",
                            DisplayPriority = (short)3,
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("e16b13a2-8698-4bb1-97dc-2fc64448e2fd"),
                            Category = "イベント情報",
                            DisplayPriority = (short)3,
                            ExpireDateTime = new DateTimeOffset(new DateTime(2024, 9, 15, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0)),
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("cfdbc43c-fae1-4a43-9772-e3bef8c955dd"),
                            Category = "重要なお知らせ",
                            DisplayPriority = (short)3,
                            IsDeleted = false,
                            PostDateTime = new DateTimeOffset(new DateTime(2024, 9, 1, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 9, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("DresscaCMS.ApplicationCore.AnnouncementContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnnouncementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.ToTable("AnnouncementsContent");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1e2b3c4-5d6f-4a7b-8c9d-0e1f2a3b4c5d"),
                            AnnouncementId = new Guid("a2c651dc-e000-473e-b064-8a1e399f93a7"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "9月25日午前2時から5時まで、システムメンテナンスのためサービスを一時停止いたします。ご利用のお客様にはご不便をおかけいたします。",
                            Title = "メンテナンスのお知らせ"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-6f7a-4b8c-9d0e-1f2a3b4c5d6e"),
                            AnnouncementId = new Guid("704945e2-ab1f-4a46-b853-d14f09e38ed4"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "現在、一部のユーザーにおいてログインできない障害が発生しております。原因を調査中であり、復旧まで今しばらくお待ちください。",
                            Title = "障害情報（ログイン）"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-7a8b-4c9d-0e1f-2a3b4c5d6e7f"),
                            AnnouncementId = new Guid("c738b93c-06ef-44be-9bb8-87fe0c3f6151"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "新しい会員向けダッシュボード機能を公開しました。利用状況やお知らせを一目で確認できるようになり、利便性が向上しました。",
                            Title = "ダッシュボード機能追加のお知らせ"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-8b9c-4d0e-1f2a-3b4c5d6e7f8a"),
                            AnnouncementId = new Guid("5030af08-13b9-478f-96d3-77e68225ebec"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "10月10日に開催されるオンラインセミナー「最新クラウド活用術」の参加受付を開始しました。ぜひお申し込みください。",
                            Title = "オンラインセミナーのご案内"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-9c0d-4e1f-2a3b-4c5d6e7f8a9b"),
                            AnnouncementId = new Guid("8721cd7a-f8cb-4d00-b5c8-53ce5eeac062"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "本社オフィスは11月1日より新住所へ移転いたします。詳細な所在地やアクセス方法は会社概要ページをご確認ください。",
                            Title = "本社移転のお知らせ"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-0d1e-4f2a-3b4c-5d6e7f8a9b0c"),
                            AnnouncementId = new Guid("da1cc949-385e-44b3-a7d1-3f489cf2347d"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "年末年始休業期間は12月29日から1月3日までとなります。休業中のお問い合わせは1月4日以降に順次対応いたします。",
                            Title = "年末年始の営業について"
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-1e2f-4a3b-4c5d-6e7f8a9b0c1d"),
                            AnnouncementId = new Guid("9eabc9d8-39af-472b-afbc-1f7e5ac61899"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "定期メンテナンスを9月30日22時より実施いたします。作業中はログインや一部機能がご利用いただけませんので、あらかじめご了承ください。",
                            Title = "メンテナンスのお知らせ"
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-2f3a-4b4c-5d6e-7f8a9b0c1d2e"),
                            AnnouncementId = new Guid("f46e232c-ce77-408d-924e-aeaff126a639"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "メール送信システムに不具合が発生し、通知メールが届かない状況です。復旧対応を進めておりますのでご不便をおかけいたします。",
                            Title = "障害情報（メール送信）"
                        },
                        new
                        {
                            Id = new Guid("c9d0e1f2-3a4b-4c5d-6e7f-8a9b0c1d2e3f"),
                            AnnouncementId = new Guid("85355a45-24d1-4b1d-98cd-d073f2ccfa02"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "本日よりオンライン決済にクレジットカード以外に電子マネー決済が追加されました。ぜひ新しい決済方法をご利用ください。",
                            Title = "決済方法追加のお知らせ"
                        },
                        new
                        {
                            Id = new Guid("d0e1f2a3-4b5c-4d6e-7f8a-9b0c1d2e3f4a"),
                            AnnouncementId = new Guid("06d6b6c6-906c-4de8-a02a-fd0f448d9d2f"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "秋のキャンペーンイベントを10月1日より実施いたします。期間中は特別割引や限定コンテンツを用意しておりますのでご期待ください。",
                            Title = "秋のキャンペーンイベントのご案内"
                        },
                        new
                        {
                            Id = new Guid("e1f2a3b4-5c6d-4e7f-8a9b-0c1d2e3f4a5b"),
                            AnnouncementId = new Guid("c948318a-44cf-4e3a-b4a2-33a382570283"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "2026年度新卒採用エントリーの受付を開始しました。募集要項や応募方法の詳細は採用情報ページをご確認ください。",
                            Title = "2026年度新卒採用について"
                        },
                        new
                        {
                            Id = new Guid("f2a3b4c5-6d7e-4f8a-9b0c-1d2e3f4a5b6c"),
                            AnnouncementId = new Guid("450a2931-f066-4f64-920a-25d2804c4951"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "中途採用にてシステムエンジニア職の募集を開始しました。経験者の方はぜひエントリーフォームよりご応募ください。",
                            Title = "中途採用募集について"
                        },
                        new
                        {
                            Id = new Guid("a3b4c5d6-7e8f-4a9b-0c1d-2e3f4a5b6c7d"),
                            AnnouncementId = new Guid("3ed8bba8-fe95-477c-89ac-0abb586affae"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "決済システムに遅延が発生しており、処理に時間がかかる状況です。復旧作業中のため、完了次第改めてお知らせいたします。",
                            Title = "障害情報（決済）"
                        },
                        new
                        {
                            Id = new Guid("b4c5d6e7-8f9a-4b0c-1d2e-3f4a5b6c7d8e"),
                            AnnouncementId = new Guid("5ff8f1f1-29f2-4c55-ad12-90004bcb3003"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "スマートフォンアプリに「プッシュ通知」機能を追加しました。最新情報をリアルタイムでお届けしますのでぜひご活用ください。",
                            Title = "プッシュ通知機能追加のお知らせ"
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-9a0b-4c1d-2e3f-4a5b6c7d8e9f"),
                            AnnouncementId = new Guid("c8180f90-fd55-4d81-9f1e-0946d5c3d75d"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "当社主催のユーザー交流イベントを11月15日に東京本社で開催いたします。詳細や参加方法は後日お知らせいたします。",
                            Title = "ユーザー交流イベントのご案内"
                        },
                        new
                        {
                            Id = new Guid("d6e7f8a9-0b1c-4d2e-3f4a-5b6c7d8e9f0a"),
                            AnnouncementId = new Guid("f83041bb-acb0-4e73-a87f-60646616b6a3"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "現在、当社を装った不審なメールが確認されております。添付ファイルの開封やURLのクリックは行わず、削除していただきますようお願いいたします。",
                            Title = "当社をかたる不審なメールへのご注意"
                        },
                        new
                        {
                            Id = new Guid("e7f8a9b0-1c2d-4e3f-4a5b-6c7d8e9f0a1b"),
                            AnnouncementId = new Guid("bf62d39d-338d-423e-9f49-e97605c8d157"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "サーバー保守作業のため、10月5日深夜にサービスが断続的にご利用いただけなくなります。ご理解とご協力をお願いいたします。",
                            Title = "メンテナンスのお知らせ"
                        },
                        new
                        {
                            Id = new Guid("f8a9b0c1-2d3e-4f4a-5b6c-7d8e9f0a1b2c"),
                            AnnouncementId = new Guid("01182620-90c4-498e-b0a5-1a8b740ff421"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "スマートフォンアプリでのプッシュ通知が受信できない障害が発生しております。対応中ですので、復旧まで今しばらくお待ちください。",
                            Title = "障害情報（スマホアプリ）"
                        },
                        new
                        {
                            Id = new Guid("a9b0c1d2-3e4f-4a5b-6c7d-8e9f0a1b2c3d"),
                            AnnouncementId = new Guid("e16b13a2-8698-4bb1-97dc-2fc64448e2fd"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "12月1日より「冬の感謝フェア」を開催いたします。限定グッズの配布や特典をご用意しておりますので、ぜひご参加ください。",
                            Title = "冬の感謝フェアーのご案内"
                        },
                        new
                        {
                            Id = new Guid("b0c1d2e3-4f5a-4b6c-7d8e-9f0a1b2c3d4e"),
                            AnnouncementId = new Guid("cfdbc43c-fae1-4a43-9772-e3bef8c955dd"),
                            LanguageCode = "jp",
                            LinkedUrl = "",
                            Message = "現在の天候不良の影響により、一部地域で商品のお届けに遅延が発生しております。ご利用のお客様にはご迷惑をおかけしますが、何卒ご了承ください。",
                            Title = "天候不良に伴う配送遅延について"
                        });
                });

            modelBuilder.Entity("DresscaCMS.ApplicationCore.AnnouncementContent", b =>
                {
                    b.HasOne("DresscaCMS.ApplicationCore.Announcement", null)
                        .WithMany("AnnouncementContents")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DresscaCMS.ApplicationCore.Announcement", b =>
                {
                    b.Navigation("AnnouncementContents");
                });
#pragma warning restore 612, 618
        }
    }
}
