---
# cSpell:ignore endgroup fjogeleit markdownlint pymdown softprops textlintignore textlintrc webapps

name: ドキュメントのビルドとリリース

on:
  push:
    branches: [main]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-Beta[0-9]+'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  APP_ALESINFINY_MARIS_WEBAPP_NAME: app-alesinfiny-maris-docs-prod
  DOCUMENT_FOLDER_PATH: documents/build-artifacts/
  DOCUMENT_ARTIFACTS_FILENAME: docs.zip

jobs:
  build:
    name: ドキュメントのビルド
    runs-on: ubuntu-latest
    outputs:
      is_pre_release: ${{ steps.setup-variables.outputs.is_pre_release }}
    steps:
      - name: ブランチのチェックアウト
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - id: setup-variables
        name: 変数の初期化
        run: |
          pre_release=false
          if [[ "${{ github.ref_name }}" == *"Beta"* ]]; then
            pre_release=true
          fi
          echo "is_pre_release:$pre_release"
          echo "is_pre_release=$pre_release" >> $GITHUB_ENV
          echo "is_pre_release=$pre_release" >> $GITHUB_OUTPUT

      - name: ドキュメントのビルド
        uses: ./.github/workflows/build-documents

      - name: ビルドアーティファクトのパッケージングとアップロード
        uses: ./.github/workflows/pack-and-upload
        with:
          packaging_folder_path: ${{ env.DOCUMENT_FOLDER_PATH }}
          document_artifact_filename: ${{ env.DOCUMENT_ARTIFACTS_FILENAME }}

  release-github:
    name: Githubのリリース
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: ビルドアーティファクトのダウンロード
        uses: actions/download-artifact@v4
        with:
          name: documents

      - name: Githubのリリース
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.DOCUMENT_ARTIFACTS_FILENAME }}
          generate_release_notes: true
          prerelease: ${{ needs.build.outputs.is_pre_release }}

  release-documents:
    name: ドキュメントのリリース
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: ビルドアーティファクトのダウンロード
        uses: actions/download-artifact@v4
        with:
          name: documents

      - name: Azure に OIDC Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ステージング環境へのデプロイ
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_ALESINFINY_MARIS_WEBAPP_NAME }}
          slot-name: staging
          package: "${{ env.DOCUMENT_ARTIFACTS_FILENAME }}"

      - name: Teams への通知
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.ALESINFINY_POST_MESSAGE_TO_TEAMS_URL  }}
          method: POST
          contentType: application/json
          data: '{"messageType": 0,"branchName": "${{ github.ref }}","actor": "${{ github.actor }}","sha": "${{ github.sha }}","eventName": "${{ github.event_name }}"}'
          timeout: 30000

  swap:
    name: 本番環境への反映承認
    needs: [release-github, release-documents]
    if: needs.build.outputs.is_pre_release == 'false' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: 本番環境への反映承認
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.ALESINFINY_APPROVE_REQUEST_TO_TEAMS_URL  }}
          method: POST
          contentType: application/json
          data: '{"branchName": "${{ github.ref }}","actor": "${{ github.actor }}","sha": "${{ github.sha }}","eventName": "${{ github.event_name }}"}'
          preventFailureOnNoResponse: true
