name: openapi-generatorのバージョンアップ確認
on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/check-openapi-generator-update.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
permissions:
    contents: read
    issues: write
jobs:
  check-update:
    name: openapi-generatorのバージョンアップ確認
    runs-on: ubuntu-latest
    steps:
      - name: ライブラリ側のバージョン取得
        id: get-lib-version
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.github.com/repos/OpenAPITools/openapi-generator/releases/latest'
          method: 'GET'
          customHeaders: '{"Content-Type": "application/json"}'

      - name: レスポンスの分析
        run: |
          echo ${{ steps.get-lib-version.outputs.response }}
          echo ${{ steps.get-lib-version.outputs.headers }}
          echo ${{ steps.get-lib-version.outputs.status }}
          echo ${{ fromJson(steps.get-lib-version.outputs.response).tag_name }} >> $GITHUB_STEP_SUMMARY
          echo "LIB_VERSION=${{ fromJson(steps.get-lib-version.outputs.response).tag_name }}" >> $GITHUB_ENV

      - name: チェックアウト
        uses: actions/checkout@v4

      - name: アプリ側のバージョン取得
        run: |
          echo "APP_VERSION=$(jq -r '.["generator-cli"].version' ./samples/Dressca/dressca-frontend/openapitools.json)" >> $GITHUB_ENV

      - name: アップデート要否を判定
        id: check_version
        run: |
          echo "UPDATE_REQUIRED=false" >> $GITHUB_ENV

      - name: サマリに出力
        run: |
          echo "openapi-generator のバージョンは ${{ env.LIB_VERSION }} です。" >> $GITHUB_STEP_SUMMARY
          echo "openapitools.json の openapi-generator のバージョンは ${{ env.APP_VERSION }} です。" >> $GITHUB_STEP_SUMMARY
          echo "アップデート要否の判定結果は ${{ env.UPDATE_REQUIRED }} です。">> $GITHUB_STEP_SUMMARY

      - name: issue を作成
        id: create-issue
        if: ${{ env.UPDATE_REQUIRED }} == true
        uses: JasonEtco/create-an-issue@v2
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: issue の情報を出力
        if: ${{ env.UPDATE_REQUIRED }} == true
        run: |
          echo "Created issue number ${{ steps.create-issue.outputs.number }}"
          echo "Created ${{ steps.create-issue.outputs.url }}"




