---
name: dressca-backend CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'samples/Dressca/dressca-backend/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: samples/Dressca/dressca-backend

jobs:
  build:
    name: バックエンドアプリケーションのビルド
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      BUILD_CONFIGURATION: Debug

    steps:
      - name: ブランチのチェックアウト
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: .NET SDK のセットアップ
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 6.0.x
          include-prerelease: false

      - name: NuGet パッケージの復元
        run: dotnet restore

      - name: アプリケーションのビルド
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}

      - name: 単体テストの実行
        run: |
          dotnet add tests/Dressca.UnitTests/Dressca.UnitTests.csproj package coverlet.msbuild
          dotnet test --no-build --verbosity normal --configuration ${{ env.BUILD_CONFIGURATION }} /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov > testResult.txt
          echo '# Coverage :rocket:' >> $GITHUB_STEP_SUMMARY
          cat testResult.txt | sed -n -e '/Calculating coverage result.../,/Average/p' | sed -e '$ a +---------+--------+--------+--------+' | sed -e 's/^\|//' | sed -e 's/\|\$//' >> $GITHUB_STEP_SUMMARY
        
