---

name: dressca-consumer-frontend CI

permissions:
  contents: read

on:
  pull_request:
    branches: [main]
    paths:
      - 'samples/Dressca/dressca-frontend/*.*'
      - 'samples/Dressca/dressca-frontend/consumer/**'
      - '.github/workflows/samples-dressca-consumer-frontend.ci.yml'
  workflow_dispatch:

defaults:
  run:
    working-directory: samples/Dressca/dressca-frontend/

jobs:
  build:
    name: Dressca Consumer フロントエンドアプリケーションのビルド
    runs-on: ubuntu-latest
    env:
      NO_COLOR: "1"  # 文字化け防止のためカラーコードを出力しない
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      - name: Use Node.js LTS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4.4.0
        with:
          node-version: lts/*
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4.3.0
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: node パッケージのキャッシュ確認
        run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'

      - name: node パッケージのインストール
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: npm ci

      - id: run-lint
        name: lintの実行
        run: npm run lint:ci:consumer >> /var/tmp/lint-result.txt 2>&1

      - id: run-type-check
        name: TypeScript の型チェック
        run: npm run type-check:consumer >> /var/tmp/type-check-result.txt 2>&1

      - id: application-build
        name: アプリケーションのビルド
        run: npm run build-only:dev:consumer >> /var/tmp/build-result.txt 2>&1

      - id: run-unit-tests
        name: 単体テストの実行
        run: npm run test:unit:consumer >> /var/tmp/unit-test-result.txt 2>&1

      - name: lintの結果出力
        if: ${{ success() || (failure() && steps.run-lint.conclusion == 'failure') }}
        uses: ./.github/workflows/file-to-summary
        with:
          body: /var/tmp/lint-result.txt
          header: 'lintの結果 :pen:'

      - name: 型チェックの結果出力
        if: ${{ success() || (failure() && steps.run-type-check.conclusion == 'failure') }}
        uses: ./.github/workflows/file-to-summary
        with:
          body: /var/tmp/type-check-result.txt
          header: '型チェックの結果 :pencil2:'

      - name: ビルドの結果出力
        if: ${{ success() || (failure() && steps.application-build.conclusion == 'failure') }}
        uses: ./.github/workflows/file-to-summary
        with:
          body: /var/tmp/build-result.txt
          header: 'ビルドの結果 :gear:'

      - name: 単体テストの結果出力
        if: ${{ success() || (failure() && steps.run-unit-tests.conclusion == 'failure') }}
        uses: ./.github/workflows/file-to-summary
        with:
          body: /var/tmp/unit-test-result.txt
          header: '単体テストの結果 :memo:'